### ISSUE TITLE
想请教一下为何reply函数里要使用`requestAnimationFrame`呢

### ISSUE THREAD

**Issue by dayzhou** [dongyuwei/tiny-wechat-robot#2]
谢谢~

**Comment by dongyuwei** [comment]
没有啥特别的，`requestAnimationFrame` https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame 只是尽量不block浏览器响应用户操作。这里去掉也不会有什么影响。

**Comment by dayzhou** [comment]
Okay，感谢
