### ISSUE TITLE
请问可以通过c++程序，调用wechaty给某个好友发消息么？

### ISSUE THREAD

**Issue by opengpu** [dongyuwei/tiny-wechat-robot#3]
请问可以通过c++程序，调用wechaty给某个好友发消息么？

**Comment by dongyuwei** [comment]
wechaty是什么?

**Comment by opengpu** [comment]
tiny-wechat-robot可以吗?

**Comment by opengpu** [comment]
请问可以通过c++程序，调用tiny-wechat-robot给某个好友发消息么？

**Comment by dongyuwei** [comment]
tiny-wechat-robot是基于js的。可以提供http api来实现。

**Comment by opengpu** [comment]
启动tiny wechat robot，把它作为本地服务器监听http消息？现在实现了么？
还是说我需要自己加上这部分功能

**Comment by dongyuwei** [comment]
现在没有实现。需要自己加上，也不难。

**Comment by opengpu** [comment]
哦，目前就是一个最简化的ping-pong应答机器人？
查到的微信bot都是模拟 网页版微信，为什么啊？
没有模拟pc版微信的么？

**Comment by opengpu** [comment]
那我先用mojo-weixin把，他好像有现成的，可以监听http发消息

**Comment by dongyuwei** [comment]
网页版微信更容易hack吧。

**Comment by opengpu** [comment]
嗯嗯，http直接明文了啊，哈哈哈
