### ISSUE TITLE
wechat web接口保留历史聊天记录的问题

### ISSUE THREAD

**Issue by sadboy-cn** [dongyuwei/tiny-wechat-robot#4]
你好，在通过微信web端的接口请求到聊天记录之后，带有FromUserName字段，但是下一次登录，同一个用户发送的FromUserName也不一样，是否有方式能保存聊天记录，第二次显示上一次该用户的聊天记录，是否还有其他实现方式

**Comment by dongyuwei** [comment]
目前我还不知道， nick name稍微稳定一些。

**Comment by sadboy-cn** [comment]
谢谢解答
